// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nativewind from "./Nativewind.bs.js";
import * as ExpoStatusBar from "expo-status-bar";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptPng from "../assets/rescript.png";
import ReactNativePng from "../assets/react-native.png";

var rescript_logo = RescriptPng;

var nativewind_logo = ReactNativePng;

function Main$main(props) {
  return JsxRuntime.jsxs(Nativewind.StyledView.make, {
              className: "flex-1 items-center justify-start",
              children: [
                JsxRuntime.jsx(Nativewind.StyledImage.make, {
                      className: "scale-[0.2] m-0",
                      source: rescript_logo
                    }),
                JsxRuntime.jsx(Nativewind.StyledImage.make, {
                      className: "m-0 opacity",
                      source: nativewind_logo
                    }),
                JsxRuntime.jsx(Nativewind.StyledText.make, {
                      className: "text-red-800",
                      children: "Rescript + ReactNative + Nativewind + Expo"
                    }),
                JsxRuntime.jsx(ExpoStatusBar.StatusBar, {
                      style: "auto"
                    })
              ]
            });
}

var main = Main$main;

export {
  rescript_logo ,
  nativewind_logo ,
  main ,
}
/* rescript_logo Not a pure module */
