// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Nativewind from "./Nativewind.bs.js";
import * as ReactNative from "react-native";
import * as ExpoStatusBar from "expo-status-bar";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptPng from "../assets/rescript.png";
import ReactNativePng from "../assets/react-native.png";

var rescript_logo = RescriptPng;

var nativewind_logo = ReactNativePng;

function Main$main(props) {
  var match = React.useState(function () {
        return "bg-black";
      });
  var set_bg = match[1];
  return JsxRuntime.jsxs(Nativewind.StyledView.make, {
              className: "flex-1 items-center justify-start " + match[0],
              children: [
                JsxRuntime.jsx(Nativewind.StyledImage.make, {
                      source: rescript_logo,
                      className: "scale-[0.2] m-0"
                    }),
                JsxRuntime.jsx(ReactNative.Button, {
                      onPress: (function (param) {
                          set_bg(function (bg) {
                                switch (bg) {
                                  case "bg-black" :
                                      return "bg-white";
                                  case "bg-white" :
                                      return "bg-black";
                                  default:
                                    return "bg-white";
                                }
                              });
                        }),
                      title: "toggle"
                    }),
                JsxRuntime.jsx(Nativewind.StyledImage.make, {
                      source: nativewind_logo,
                      className: "m-0"
                    }),
                JsxRuntime.jsx(Nativewind.StyledText.make, {
                      className: "text-red-800 border-[10]",
                      children: "Rescript + ReactNative + Nativewind + Expo"
                    }),
                JsxRuntime.jsx(ExpoStatusBar.StatusBar, {
                      style: "auto"
                    })
              ]
            });
}

var main = Main$main;

export {
  rescript_logo ,
  nativewind_logo ,
  main ,
}
/* rescript_logo Not a pure module */
