// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nativewind from "nativewind";
import * as ReactNative from "react-native";

var make = Nativewind.styled(ReactNative.Text);

var StyledText = {
  make: make
};

var make$1 = Nativewind.styled(ReactNative.View);

var StyledView = {
  make: make$1
};

var make$2 = Nativewind.styled(ReactNative.Image);

var StyledImage = {
  make: make$2
};

export {
  StyledText ,
  StyledView ,
  StyledImage ,
}
/* make Not a pure module */
